### PR TITLE
fix: refactor wireguard vpn model to reflect native support

### LINKED ISSUE #133: [BUG] VPN device path "/" causes "UnknownDevice" error
**Describe the bug**
Using `OwnedObjectPath::try_from("/")` for the device path causes NetworkManager to try using the loopback device

```log
➜ cargo run
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/throwing`
Setting up WireGuard VPN connection...
✗ Failed to connect: D-Bus error: org.freedesktop.NetworkManager.UnknownDevice: No suitable device found for this connection (device lo not available because profile is not compatible with device (connection type is not "loopback")).
```

My code in question:

```rust
use nmrs::{NetworkManager, VpnCredentials, VpnType, WireGuardPeer};

#[tokio::main]
async fn main() -> nmrs::Result<()> {
    let nm = NetworkManager::new().await?;
    
    let vpn_config = VpnCredentials {
        vpn_type: VpnType::WireGuard,
        name: "MyWireGuard".into(),
        gateway: "1.2.3.4:51820".into(),
        private_key: "PRIVATE_KEY".into(),
        address: "10.0.0.2/24".into(),
        dns: Some(vec!["1.1.1.1".into()]),
        mtu: None,
        uuid: Some(uuid::Uuid::new_v4()),
        peers: vec![
            WireGuardPeer {
                public_key: "PUBLIC_KEY".into(),
                gateway: "1.2.3.4:51820".into(),
                preshared_key: None,
                allowed_ips: vec!["0.0.0.0/0".into()],
                persistent_keepalive: Some(25),
            }
        ],
    };
    
    nm.connect_vpn(vpn_config).await?;
    Ok(())
}
```
**What should happen?:**

The VPN connection should be created and activated, bound to the currently active network device (e.g., `wlan0` or whatever). The library should automatically detect the active device and use its D-Bus object path instead of passing "/", which NetworkManager incorrectly interprets as the loopback device.

**Additional context**

### PR DESCRIPTION
**Pull request by tuned-willow**
This replaces the previous VPN-style WireGuard configuration with NetworkManager’s native `connection.type=wireguard` profile structure. The prior format treated WireGuard as a VPN plugin and produced invalid or partially-applied settings. The new implementation builds a proper WireGuard connection, writes peers in the expected schema, and activates via the Settings API to avoid device validation failures during creation.

* Switch `connection.type` from `vpn` to `wireguard`
* Move WireGuard fields into a dedicated `[wireguard]` section
* Represent peers as structured entries (public-key, endpoint, allowed-ips, optional preshared-key, keepalive)
* Use Settings API add-then-activate flow for more reliable activation
* Tighten disconnect/list logic to target WireGuard connections explicitly
* Improve post-activation verification to catch immediate deactivation

Closes #133

### CODE REVIEW

File: nmrs/src/core/vpn.rs [hunk 1]
```diff
@@ -59,22 +58,99 @@ pub(crate) async fn connect_vpn(conn: &Connection, creds: VpnCredentials) -> Res
...
+            .await?
     };
 
     wait_for_connection_activation(conn, &active_conn).await?;
-
-    info!("Successfully connected to VPN: {}", creds.name);
-    Ok(())
+    debug!("Connection reached Activated state, waiting briefly...");
+
+    // NetworkManager can report Activated before the tunnel is fully usable.
```
Comment (cachebag) [inline nmrs/src/core/vpn.rs]: Since we've handled activating the connection AFTER adding the connection itself, this delay may not be needed at all.
